### PR TITLE
A bit of work towards 1.10.2

### PR DESCRIPTION
**Pull request by DiMuRie**
@MrCrayfish you still have to finish it but i already done 1/2 work.u only need to do bugfixes now!oh...and ass the other theme blocks

### CODE REVIEW

**Comment by MrCrayfish** [comment]
Thanks dude for all your help! Will refactor a few parts here and there but this is pretty much an awesome start. I'll definitely add you to the credits of the mod.

**Comment by DiMuRie** [comment]
thanks!

**Comment by DiMuRie** [comment]
btw i made the colisions badly.can you change it from
colidingBoxes.add();
to
addCollisionBoxToList(pos, entityBox, collidingBoxes, RESPECTIVE_AABB);

**Comment by MrCrayfish** [comment]
That's okay. This is definitely a head start for me though.

**Comment by DiMuRie** [comment]
BTW:unrelated,but can i pledge to you using curse:like transfer 20 points and get the 1$ patreon reward?

**Comment by MrCrayfish** [comment]
I don't really use Curse, nor is there any way for me to manually add you as a Patreon. What do you specifally need from the $1 reward?If it;s the source code, I can send it once. However you'll have to nag me to get any updated sources because I can't put on my plate to personally send you the sources each time they change.

**Comment by DiMuRie** [comment]
Nvm curse says you're not in the reward point program

**Pull request merged**
